import type { Course, Instructor } from "@/types";

export const instructors: Instructor[] = [
  {
    id: "ins-1",
    name: "Dr. Layla Hassan",
    title: "Senior Software Engineer",
    avatar: "https://i.pravatar.cc/160?img=47",
    rating: 4.9,
    students: 82400,
  },
  {
    id: "ins-2",
    name: "Marcus Reed",
    title: "Product Design Lead",
    avatar: "https://i.pravatar.cc/160?img=12",
    rating: 4.8,
    students: 51200,
  },
  {
    id: "ins-3",
    name: "Sofia Marín",
    title: "Growth Marketing Strategist",
    avatar: "https://i.pravatar.cc/160?img=32",
    rating: 4.7,
    students: 38900,
  },
  {
    id: "ins-4",
    name: "Kenji Watanabe",
    title: "Award-winning Photographer",
    avatar: "https://i.pravatar.cc/160?img=59",
    rating: 4.9,
    students: 27600,
  },
];

const img = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=800&q=70`;

export const courses: Course[] = [
  {
    id: "c-1",
    slug: "fullstack-typescript",
    title: "Full-Stack Development with TypeScript & Next.js",
    thumbnail: img("photo-1516116216624-53e697fedbea"),
    category: "programming",
    instructor: instructors[0],
    rating: 4.9,
    reviews: 12840,
    durationHours: 42,
    lessons: 186,
    level: "Intermediate",
    price: 89,
    originalPrice: 199,
    bestseller: true,
  },
  {
    id: "c-2",
    slug: "product-design-mastery",
    title: "Product Design Mastery: From Wireframe to Prototype",
    thumbnail: img("photo-1561070791-2526d30994b5"),
    category: "design",
    instructor: instructors[1],
    rating: 4.8,
    reviews: 9310,
    durationHours: 28,
    lessons: 120,
    level: "Beginner",
    price: 74,
    originalPrice: 149,
    bestseller: true,
  },
  {
    id: "c-3",
    slug: "growth-marketing-2025",
    title: "Growth Marketing: Data-Driven Campaigns that Convert",
    thumbnail: img("photo-1460925895917-afdab827c52f"),
    category: "marketing",
    instructor: instructors[2],
    rating: 4.7,
    reviews: 6720,
    durationHours: 19,
    lessons: 88,
    level: "Intermediate",
    price: 64,
  },
  {
    id: "c-4",
    slug: "photography-foundations",
    title: "Photography Foundations: Light, Composition & Story",
    thumbnail: img("photo-1452587925148-ce544e77e70d"),
    category: "photography",
    instructor: instructors[3],
    rating: 4.9,
    reviews: 4180,
    durationHours: 16,
    lessons: 74,
    level: "Beginner",
    price: 54,
    originalPrice: 99,
  },
  {
    id: "c-5",
    slug: "scaling-startups",
    title: "Scaling Startups: Strategy, Ops & Fundraising",
    thumbnail: img("photo-1454165804606-c3d57bc86b40"),
    category: "business",
    instructor: instructors[2],
    rating: 4.6,
    reviews: 3120,
    durationHours: 22,
    lessons: 96,
    level: "Advanced",
    price: 99,
    originalPrice: 189,
  },
  {
    id: "c-6",
    slug: "conversational-arabic",
    title: "Conversational Arabic for Real-World Fluency",
    thumbnail: img("photo-1503676260728-1c00da094a0b"),
    category: "languages",
    instructor: instructors[0],
    rating: 4.8,
    reviews: 2890,
    durationHours: 30,
    lessons: 140,
    level: "Beginner",
    price: 49,
  },
];

export const featuredCourses = courses.slice(0, 4);
